"""node_entity_id

Revision ID: e08f48a94604
Revises: 75be5275e1b7
Create Date: 2020-02-27 23:26:02.251327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08f48a94604'
down_revision = '75be5275e1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('node_entity_id', sa.Integer(), nullable=True))
    op.add_column('points', sa.Column('node_entity_id', sa.Integer(), nullable=True))
    op.add_column('types', sa.Column('node_entity_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'node_entity_id')
    op.drop_column('points', 'node_entity_id')
    op.drop_column('plants', 'node_entity_id')
    # ### end Alembic commands ###
